# Background and foreground colors
background = #1a1a1a
foreground = #696969

# Standard colors
palette = 0=#1a1a1a
palette = 1=#ff0000
palette = 2=#00c800
palette = 3=#ffb800
palette = 4=#0e00de
palette = 5=#acacac
palette = 6=#dadada
palette = 7=#696969

# Bright colors
palette = 8=#434343
palette = 9=#930000
palette = 10=#009300
palette = 11=#dfae00
palette = 12=#1d00a2
palette = 13=#bfbfbf
palette = 14=#eeeeee
palette = 15=#696969
