background            #1a1a1a
foreground            #696969

# black
color0  #1a1a1a
color8  #434343

# red
color1  #ff0000
color9  #930000

# green
color2  #00c800
color10 #009300

# yellow
color3  #ffb800
color11 #dfae00

# blue
color4  #0e00de
color12 #1d00a2

# magenta
color5  #acacac
color13 #bfbfbf

#cyan
color6  #dadada
color14 #eeeeee

#white
color7  #696969
color15 #696969


